window.ReviewApp.content.register({
type: "notes",
cert: "linux-plus",
chapter: "Ch 2 · Linux Server Services & Configuration",
items: [
{
title: "Server Architecture, Ports & Core Internet Services",
body: "## Server Models\n- **Daemon**: Background process (ends in \\d\) listening for client requests (e.g., \\mysqld\).\n- **Super-server**: Listens on behalf of multiple services; spawns app on demand. Legacy \\inetd\/\\xinetd\ replaced by **systemd** unit files.\n\n## Well-Known Ports\n| Port | Protocol | Service |\n|------|----------|---------|\n| 20/21 | FTP | File Transfer |\n| 22 | SSH | Secure Shell |\n| 23 | Telnet | Unsecure remote shell |\n| 25 | SMTP | Mail transport |\n| 53 | DNS | Name resolution |\n| 67 | DHCP | IP address assignment |\n| 80 | HTTP | Web traffic |\n| 109/110 | POP | Mail retrieval |\n| 137-139 | SMB | Windows file/print sharing |\n| 143, 220 | IMAP | Advanced mail access |\n| 389 | LDAP | Directory services |\n| 443 | HTTPS | Encrypted web |\n| 2049 | NFS | Linux/Unix file sharing |\n\n## Web Servers\n| Server | Config File | Extra Config Dir | Default DocumentRoot |\n|--------|-------------|------------------|----------------------|\n| **Apache** | \\/etc/httpd/httpd.conf\ | \\/etc/httpd/conf.d/\ | \\/var/www/html\ |\n| **Nginx** | \\/etc/nginx/nginx.conf\ | \\/etc/nginx/conf.d/\ | \\/usr/share/nginx/html\ |\n| **lighthttpd** | Lightweight, low resource | Embedded/IoT use | — |\n\n- **Apache**: Modular (load only needed modules: SSL, PHP, rewrite).\n- **Nginx**: Event-driven, smaller footprint, built-in reverse proxy/load balancer/caching. Often placed in front of Apache.\n\n## Database Servers\n| DB | Type | Key Traits |\n|----|------|------------|\n| **PostgreSQL** | Relational (ORDBMS) | ACID, transactions, stored procedures, extensible |\n| **MySQL** | Relational (RDBMS) | LAMP stack, performance-focused, multiple storage engines |\n| **MongoDB** | NoSQL (Document) | JSON-like BSON documents, flexible schema, sharding, replication |\n\n## Mail Architecture\n1. **MUA** (Mail User Agent): Client app — Evolution, Thunderbird, KMail.\n2. **MTA** (Mail Transfer Agent): Routes/sends mail via SMTP.\n3. **MDA** (Mail Delivery Agent): Delivers to local mailbox.\n\n### MTA Packages\n| MTA | Model | Config | Notes |\n|-----|-------|--------|-------|\n| **sendmail** | Monolithic | \\/etc/mail/sendmail.cf\ (auto-generated from \\sendmail.mc\) | Complex, powerful |\n| **Postfix** | Modular | \\/etc/postfix/main.cf\, \\/etc/postfix/master.cf\ | Simple, two plain-text files |\n| **Exim** | Monolithic | \\/etc/exim.conf\ | Favors immediate delivery |\n\n### MDA & Mailbox\n- **Binmail** (\\/bin/mail\): Default spool at \\/var/spool/mail\.\n- **Procmail**: User-defined filtering via \\~/.procmailrc\ using regex recipes.\n- **Dovecot**: IMAP4 server. Config: \\/etc/dovecot/dovecot.conf\ + \\/etc/dovecot/conf.d/\.",
tags: ["daemon", "ports", "web-server", "database", "mail", "mta", "mda", "apache", "nginx", "lamp"]
},
{
title: "Local Network Services, Security & Performance",
body:" ## File & Print Sharing\n- **NFS** (\\nfs-utils\): Linux/Unix folder sharing. Mount remote folders like local partitions. Port **2049**.\n- **Samba**: Implements Microsoft **SMB** protocol. Linux ↔ Windows file/print sharing.\n- **CUPS**: Standard Linux printing. Uses **IPP** (Internet Printing Protocol).\n\n## Network Infrastructure\n| Service | Package/Daemon | Config File | Purpose |\n|---------|---------------|-------------|---------|\n| **DHCP** | \\dhcpd\ (ISC) | \\/etc/dhcp/dhcpd.conf\ | Auto IP assignment |\n| **DNS** | BIND (\\named\) | \\named.conf\ | Hostname ↔ IP resolution |\n| **DNS** (Systemd) | \\systemd-resolved\ | \\/etc/systemd/network/\*.network\ | Modern DNS service |\n| **NTP** | \\ntpd\ | \\/etc/ntpd.conf\ | Time sync |\n| **NTP** | \\chronyd\ | \\/etc/chrony.conf\ | Time sync (modern) |\n| **Logging** | \\rsyslogd\ | — | Remote logging (SysVinit/Upstart) |\n| **Logging** | \\journald\ | — | Remote logging (Systemd) |\n\n- **SNMP** (\\net-snmp\, UDP **161-162**): Remote monitoring. v3 = strong auth + encryption.\n\n## Security Layers\n| Technology | Purpose |\n|------------|---------|\n| **NIS** (YP) | Shared naming directory (user accounts, hostnames) |\n| **Kerberos** | Symmetric-key encrypted authentication (MIT) |\n| **LDAP** (OpenLDAP) | Hierarchical directory authentication |\n| **OpenSSL** | Certificate Authority (CA) — two-factor auth (cert + PIN) |\n| **OpenSSH** | Encrypted remote access (replaces Telnet/FTP); supports tunneling |\n| **OpenVPN** | Secure point-to-point VPN tunnel for remote network access |\n\n## Performance\n- **Clustering**: Multiple nodes share workload (e.g., Hadoop, LVS). Not ideal for all DB apps due to locking overhead.\n- **Load Balancing**: Distributes client requests across cluster nodes. Tools: **HAProxy**, **LVS**, **Nginx**.\n- **Containers**: Portable app bundles (Docker, Kubernetes). Eliminates \"works on my machine\" issues.",
tags: ["nfs", "samba", "cups", "dhcp", "dns", "ntp", "snmp", "security", "ssh", "vpn", "ldap", "kerberos", "clustering", "load-balancing", "containers", "docker"]
}
]
});